#- hosts: all
#
#  vars:
#    WWW_BASE_PATH: "/var/www"
#    DOMAIN_NAME: "mydomain.com"
#    WORDPRESS_INSTALL_URL: "https://wordpress.org/wordpress-6.4.3.tar.gz"

- name: Update and Upgrade the Server
  hosts: all
  become: yes
  roles:
    - server
- name: Install PHP
  hosts: all
  become: yes
  roles:
    - php
- name: Install MySQL
  hosts: all
  become: yes
  roles:
    - geerlingguy.mysql
- name: Install Nginx
  hosts: all
  become: yes
  roles:
    - nginx
- name: Install Wordpress
  hosts: all
  become: yes
  roles:
    - wordpress
