
- name: Create directory for site
  ansible.builtin.file:
    path: "{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Check the file 
  ansible.builtin.stat:
    path: "{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}/wp-settings.php"
  register: file_check

- name: Download Wordpress 6.4.3
  ansible.builtin.get_url:
    url: https://wordpress.org/wordpress-6.4.3.tar.gz
    dest: "{{ WWW_BASE_PATH }}/" 
  when: file_check.stat.exists == false

- name: Extract wordpress-6.4.3.tar.gz
  ansible.builtin.unarchive:
    src: /var/www/wordpress-6.4.3.tar.gz
    dest: "{{ WWW_BASE_PATH }}/" 
    remote_src: yes
  when: file_check.stat.exists == false

- name: Move extracted files
  ansible.builtin.copy:
    src: "{{ WWW_BASE_PATH }}/wordpress/"
    dest: "{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}/"
    remote_src: true
    owner: www-data
    group: www-data
  when: file_check.stat.exists == false

- name: Delete unused directories and files
  ansible.builtin.file:
      path: "{{ item }}"
      state: absent
  loop:
     - /var/www/wordpress-6.4.3.tar.gz
     - /var/www/wordpress
     
- name: Download Wordpress CLI
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /var/www/
  when: file_check.stat.exists == false

- name: Move extracted files
  ansible.builtin.copy:
    src: /var/www/wp-cli.phar
    dest: /usr/local/bin/wp
    remote_src: true
    owner: www-data
    group: www-data
    mode: '0755'
  when: file_check.stat.exists == false

- name: Check if wp-config.php exists 
  stat:
    path: /var/www/mydomain.com/wp-config.php 
  register: result

- name: Show result
  debug:
    msg: "wp-config.php does not exist!"
  when: not result.stat.exists
  
- name: Configure Wordpress Connection to DB
  ansible.builtin.shell: 
    cmd: wp config create --dbname=wordpress --dbuser=user --dbpass=mypassword --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}/' --allow-root 
  when: not result.stat.exists

- name: Configure Wordpress Installation
  ansible.builtin.shell:
    cmd: wp core multisite-install --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --url='{{ DOMAIN_NAME }}' --title='My Domain' --admin_user=wpadmin --admin_password=mypassword --admin_email='thesodabar@gmail.com' --skip-email --subdomains --allow-root
    
- name: Wordpress Update Core System
  ansible.builtin.shell:
    cmd: wp core update --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --allow-root

- name: Wordpress Install Plugin Instagram Widge by WPZOOM
  ansible.builtin.shell:
    cmd: wp plugin install --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --activate  'https://downloads.wordpress.org/plugin/instagram-widget-by-wpzoom.2.1.19.zip' --allow-root

- name:  Wordpress Install Plugin Visual Link Preview
  ansible.builtin.shell:
    cmd: wp plugin install --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --activate  'https://downloads.wordpress.org/plugin/visual-link-preview.zip' --allow-root
    
- name:  Wordpress Install Plugin Google Site Kit
  ansible.builtin.shell:
    cmd: wp plugin install --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --activate  'https://downloads.wordpress.org/plugin/google-site-kit.1.137.0.zip' --allow-root

- name:  Wordpress Install Theme Kadence
  ansible.builtin.shell:
    cmd: wp theme install --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --activate 'https://downloads.wordpress.org/theme/kadence.1.2.9.zip' --allow-root 

- name: Wordpress Plugin Update
  ansible.builtin.shell:
    cmd: wp plugin update --all --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --allow-root

- name: Wordpress Plugin Update
  ansible.builtin.shell:
    cmd: wp theme update --all --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --allow-root

- name: Wordpress Plugin Update
  ansible.builtin.shell:
    cmd: wp core update-db --network --path='{{ WWW_BASE_PATH }}/{{ DOMAIN_NAME }}' --allow-root

    
