mysql_root_password: mypassword
mysql_databases:
  - name: wordpress
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: user
    host: "%"
    priv: "wordpress.*:ALL"
    password: mypassword
